import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import NextAuthProvider from "@/components/NextAuthProvider";
import { Providers } from "./providers";
import Sidebar from "@/components/Sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#050505] text-white selection:bg-[#1DB954] selection:text-black`}>
        <Toaster position="bottom-right" toastOptions={{ style: { background: '#111', color: '#fff', border: '1px solid #333' } }} />
        <NextAuthProvider>
          <div className="flex min-h-screen relative overflow-hidden">
            <div className="fixed inset-0 opacity-[0.15] pointer-events-none z-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')]" />
            <Sidebar />
            <main className="flex-1 ml-64 relative z-10 min-h-screen">
              <div className="max-w-7xl mx-auto px-8 py-12">
                {children}
              </div>
            </main>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
