import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./providers";
import Sidebar from "@/components/Sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="flex min-h-screen bg-black text-white">
            <Sidebar />
            <main className="flex-1 ml-64 relative">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
